# Generated by Django 2.1.7 on 2020-04-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_milestone_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
