# Generated by Django 2.1.7 on 2020-04-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200414_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='capability',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
