# Generated by Django 2.1.7 on 2020-04-14 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200414_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milestone',
            old_name='milestone',
            new_name='project',
        ),
        migrations.RemoveField(
            model_name='capability',
            name='capability',
        ),
        migrations.AddField(
            model_name='capability',
            name='milestone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Milestone'),
        ),
    ]
