# Generated by Django 2.1.7 on 2020-04-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20200414_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='capability',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='capability',
            name='product_type',
            field=models.CharField(choices=[('service', 'service'), ('tool', 'tool')], default='service', max_length=200, null=True),
        ),
    ]
