# Generated by Django 2.1.7 on 2020-04-14 18:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20200414_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='capability',
            name='requirements_link',
            field=models.URLField(default=django.utils.timezone.now, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_priority',
            field=models.CharField(choices=[('high', 'high'), ('medium', 'medium'), ('low', 'low')], default='low', max_length=200, null=True),
        ),
    ]
