# Generated by Django 2.1.7 on 2020-04-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20200414_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capability',
            options={'verbose_name_plural': 'capabilities'},
        ),
        migrations.RemoveField(
            model_name='capability',
            name='milestone_name',
        ),
        migrations.AddField(
            model_name='capability',
            name='milestone',
            field=models.ManyToManyField(null=True, to='polls.Milestone'),
        ),
        migrations.AlterField(
            model_name='capability',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
