# Generated by Django 2.1.7 on 2020-04-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20200414_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='requested_budget',
            field=models.FloatField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='capability',
            name='product_type',
            field=models.CharField(choices=[('Zeus', 'Zeus'), ('Athena', 'Athena')], default='service', max_length=200, null=True),
        ),
    ]
