# Generated by Django 2.1.7 on 2020-04-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20200427_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='approved_budget',
            field=models.FloatField(max_length=25, null=True),
        ),
    ]
