# Generated by Django 2.1.7 on 2020-04-27 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_project_approved_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='capability',
            name='project_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Project'),
        ),
    ]
