# Generated by Django 2.1.7 on 2020-04-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_capability_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ace_approved',
            field=models.BooleanField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='ace_number',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='approved_budget',
            field=models.FloatField(max_length=25),
        ),
        migrations.AlterField(
            model_name='project',
            name='requested_budget',
            field=models.FloatField(max_length=25),
        ),
    ]
