# Generated by Django 2.1.7 on 2020-04-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_capability_discovery_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='capability',
            name='target_date',
            field=models.DateField(null=True),
        ),
    ]
