# Generated by Django 2.1.7 on 2020-04-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_capability_benefit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capability',
            name='benefit',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='project_name',
            field=models.CharField(default='tbd', max_length=200, null=True),
        ),
    ]
