# Generated by Django 2.1.7 on 2020-04-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='capability',
            name='priority',
            field=models.TextField(choices=[('high', 'high'), ('medium', 'medium'), ('low', 'low')], default='low', null=True),
        ),
    ]
